rootProject.name = "grandmastery"

include("game")
include("server")
include("client")
include("gui")
include("conversation")
include("local")
include("tui")
include("bot-farm")
include("bots:ljedmitry-bot")
include("bots:melniknow-bots")
include("bots:yurkevich-bots")
include("bots:bots-factory")
include("lichess-client")